### ISSUE TITLE
Thanks and a question about performance

### ISSUE THREAD

**Issue by davidbody** [elliottmorris/toy-us-election-simulator#2]
Thanks for sharing this. It's been highly educational for me. I've studied the full model, too, but it's easy to get lost in the details and I'm still new to Stan.

I want to ask a question, though. Would you entertain a pull request to improve the performance of the main simulation? I'm talking about the code in the `pblapply` call at line 324 of `main_poll_simulator.R`. This code takes several minutes to run on my laptop, but I've written a version that produces exactly the same results in a fraction of a second.

I'd be happy to submit a pull request, or share my code another way, if it would be of interest, but I wanted to ask first because I understand this is a personal project that you shared mainly as an educational example.

Thanks again!

**Comment by elliottmorris** [comment]
David,

Sure! Please submit the PR. Make sure you pull first, though -- I did commit a few minor changes today.

E

**Comment by davidbody** [comment]
Elliott,

Will do.

The project history before today seems to have disappeared from the repository. Is that intentional?

--David

**Comment by elliottmorris** [comment]
No, and that’s very frustrating. I had to redo the use of ‘renv’ to enable packages for R 4.0 and must have run the wrong git commands.

The only thing that changed today was that revision and the addition of a new chart. Nothing in the modeling front.

**Comment by elliottmorris** [comment]
Closed by #3
